from arvore_binaria import ArvoreBinaria

arvore = ArvoreBinaria()

arvore.inserir(10)
arvore.inserir(8)
arvore.inserir(5)
arvore.inserir(7)
arvore.inserir(9)
arvore.inserir(18)
arvore.inserir(13)
arvore.inserir(20)

print("\nGrau")
print(f"Nó: 10, Grau: {arvore.grau(10)}")
print(f"Nó: 5, Grau: {arvore.grau(5)}")
print(f"Nó: 7, Grau: {arvore.grau(7)}")
print(f"Nó: 8, Grau: {arvore.grau(8)}")
print(f"Nó: 9, Grau: {arvore.grau(9)}")
print(f"Nó: 13, Grau: {arvore.grau(13)}")
print(f"Nó: 18, Grau: {arvore.grau(18)}")
print(f"Nó: 20, Grau: {arvore.grau(20)}")

print("\nProfundidade")
print(f"Nó: 10, Profundidade: {arvore.profundidade(10)}")
print(f"Nó: 5, Profundidade: {arvore.profundidade(5)}")
print(f"Nó: 7, Profundidade: {arvore.profundidade(7)}")
print(f"Nó: 8, Profundidade: {arvore.profundidade(8)}")
print(f"Nó: 9, Profundidade: {arvore.profundidade(9)}")
print(f"Nó: 13, Profundidade: {arvore.profundidade(13)}")
print(f"Nó: 18, Profundidade: {arvore.profundidade(18)}")
print(f"Nó: 20, Profundidade: {arvore.profundidade(20)}")

print("\nAltura")
print(f"Nó: 10, Altura: {arvore.altura_(10)}")
print(f"Nó: 5, Altura: {arvore.altura_(5)}")
print(f"Nó: 7, Altura: {arvore.altura_(7)}")
print(f"Nó: 8, Altura: {arvore.altura_(8)}")
print(f"Nó: 9, Altura: {arvore.altura_(9)}")
print(f"Nó: 13, Altura: {arvore.altura_(13)}")
print(f"Nó: 18, Altura: {arvore.altura_(18)}")
print(f"Nó: 20, Altura: {arvore.altura_(20)}")

print("\nNivel")
print(f"Nó: 10, Nivel: {arvore.nivel(10)}")
print(f"Nó: 5, Nivel: {arvore.nivel(5)}")
print(f"Nó: 7, Nivel: {arvore.nivel(7)}")
print(f"Nó: 8, Nivel: {arvore.nivel(8)}")
print(f"Nó: 9, Nivel: {arvore.nivel(9)}")
print(f"Nó: 13, Nivel: {arvore.nivel(13)}")
print(f"Nó: 18, Nivel: {arvore.nivel(18)}")
print(f"Nó: 20, Nivel: {arvore.nivel(20)}")

print(f"\nQuantidade de nós: {arvore.quantidadeNos(arvore.raiz)}")

print("\nIn Order")
arvore.inOrder(arvore.raiz)
print("\nPos Order")
arvore.posOrder(arvore.raiz)
print("\nPre Order")
arvore.preOrder(arvore.raiz)
print("\n")

print("\nÁrvore")
arvore.get_arvore(10)
print("\nÁrvore invertida")
arvore.get_arvore_invertida(10)

print("\nBuscar elemento \'10\'")
print(arvore.buscar(10))
print("Buscar elemento \'18\'")
print(arvore.buscar(18))
print("Buscar elemento \'5\'")
print(arvore.buscar(5))
print("Buscar elemento \'7\'")
print(arvore.buscar(7))
print("Buscar elemento \'11\'")
print(arvore.buscar(11))
print("Buscar elemento \'6\'")
print(arvore.buscar(6))
print("Buscar elemento \'2\'")
print(arvore.buscar(2))

print("\nÁrvore")
arvore.get_arvore(10)
print("\nRemover elemento \'9\', nó folha")
arvore.remover(9)
print("\nÁrvore")
arvore.get_arvore(10)
print("Remover elemento \'5\', com 1 filho")
arvore.remover(5)
print("\nÁrvore")
arvore.get_arvore(10)
print("Remover elemento \'18\', com 2 filho")
arvore.remover(18)
print("\nÁrvore")
arvore.get_arvore(10)

print(f"\nQuantidade de nós: {arvore.quantidadeNos(arvore.raiz)}")

print("\nIn Order")
arvore.inOrder(arvore.raiz)
print("\nPos Order")
arvore.posOrder(arvore.raiz)
print("\nPre Order")
arvore.preOrder(arvore.raiz)
