from arvore_generica import Arvore

no0 = Arvore(10)
no1 = Arvore(5)
no2 = Arvore(7)
no3 = Arvore(8)
no4 = Arvore(9)
no5 = Arvore(13)
no6 = Arvore(18)
no7 = Arvore(20)

no1.set_filho(no2)
no3.set_filho(no1)
no3.set_filho(no4)
no6.set_filho(no5)
no6.set_filho(no7)

no0.set_filho(no3)
no0.set_filho(no6)

print("Raiz")
no0.get_raiz()

print()
print("Nós")
no0.get_nos()

print()
print("Folhas")
no0.get_folhas()

print()
print("Grau")
print(f"Nó: {no0.elemento}, Grau: {no0.get_grau()}")
print(f"Nó: {no1.elemento}, Grau: {no1.get_grau()}")
print(f"Nó: {no2.elemento}, Grau: {no2.get_grau()}")
print(f"Nó: {no3.elemento}, Grau: {no3.get_grau()}")
print(f"Nó: {no4.elemento}, Grau: {no4.get_grau()}")
print(f"Nó: {no5.elemento}, Grau: {no5.get_grau()}")
print(f"Nó: {no6.elemento}, Grau: {no6.get_grau()}")
print(f"Nó: {no7.elemento}, Grau: {no7.get_grau()}")

print()
print("Altura")
print(f"Nó: {no0.elemento}, Altura: {no0.get_altura()}")
print(f"Nó: {no1.elemento}, Altura: {no1.get_altura()}")
print(f"Nó: {no2.elemento}, Altura: {no2.get_altura()}")
print(f"Nó: {no3.elemento}, Altura: {no3.get_altura()}")
print(f"Nó: {no4.elemento}, Altura: {no4.get_altura()}")
print(f"Nó: {no5.elemento}, Altura: {no5.get_altura()}")
print(f"Nó: {no6.elemento}, Altura: {no6.get_altura()}")
print(f"Nó: {no7.elemento}, Altura: {no7.get_altura()}")

print()
print("Profundidade")
print(f"Nó: {no0.elemento}, Profundidade: {no0.get_profundidade()}")
print(f"Nó: {no1.elemento}, Profundidade: {no1.get_profundidade()}")
print(f"Nó: {no2.elemento}, Profundidade: {no2.get_profundidade()}")
print(f"Nó: {no3.elemento}, Profundidade: {no3.get_profundidade()}")
print(f"Nó: {no4.elemento}, Profundidade: {no4.get_profundidade()}")
print(f"Nó: {no5.elemento}, Profundidade: {no5.get_profundidade()}")
print(f"Nó: {no6.elemento}, Profundidade: {no6.get_profundidade()}")
print(f"Nó: {no7.elemento}, Profundidade: {no7.get_profundidade()}")

print()
print("Nivel")
print(f"Nó: {no0.elemento}, Nivel: {no0.get_nivel()}")
print(f"Nó: {no1.elemento}, Nivel: {no1.get_nivel()}")
print(f"Nó: {no2.elemento}, Nivel: {no2.get_nivel()}")
print(f"Nó: {no3.elemento}, Nivel: {no3.get_nivel()}")
print(f"Nó: {no4.elemento}, Nivel: {no4.get_nivel()}")
print(f"Nó: {no5.elemento}, Nivel: {no5.get_nivel()}")
print(f"Nó: {no6.elemento}, Nivel: {no6.get_nivel()}")
print(f"Nó: {no7.elemento}, Nivel: {no7.get_nivel()}")

print()
print("Árvore")
no0.get_arvore()
print()
print(f"Subárvore do elemento {no1.elemento}")
no1.get_arvore()
print()
print(f"Subárvore do elemento {no2.elemento}")
no2.get_arvore()
print()
print(f"Subárvore do elemento {no3.elemento}")
no3.get_arvore()
print()
print(f"Subárvore do elemento {no4.elemento}")
no4.get_arvore()
print()
print(f"Subárvore do elemento {no5.elemento}")
no5.get_arvore()
print()
print(f"Subárvore do elemento {no6.elemento}")
no6.get_arvore()
print()
print(f"Subárvore do elemento {no7.elemento}")
no7.get_arvore()